### ISSUE TITLE
ERROR assert self.observation_space.contains(obs)

### ISSUE THREAD

**Issue by narges-sa** [bchidamb/RL-Image-Classification#1]
Hi there,
I cloned this repository and ran this command line according to run-train.sh
!python3 train.py --batch_size 32 --iters 2000000 
but I received this error:
Training...
Starting iteration 0
Traceback (most recent call last):
  File "train.py", line 133, in <module>
    main()
  File "train.py", line 17, in main
    trained_agent = train(args.iters, args.batch_size, verbose=args.verbose)
  File "train.py", line 57, in train
    observation = env.reset()
  File "/content/drive/MyDrive/Colab Notebooks/RL-Image-Classification/mnist_env.py", line 113, in reset
    return self._get_obs()
  File "/content/drive/MyDrive/Colab Notebooks/RL-Image-Classification/mnist_env.py", line 117, in _get_obs
    assert self.observation_space.contains(obs)
AssertionError

I will be grateful if you can help me to solve this problem.

**Comment by XieZixiUSTC** [comment]
assert self.observation_space.contains(obs) metoooo!!!! i encountered the same problem
